# Generated by Django 5.1.2 on 2024-11-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='reset_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
