# Generated by Django 5.1.2 on 2024-11-21 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_employees'),
        ('tickets', '0002_ticket_related_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketsTrash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmr', models.PositiveIntegerField(unique=True)),
                ('handicap', models.BooleanField(default=False)),
                ('ticket_type', models.CharField(choices=[('Retrait ou dépôt argent', 'Retrait ou dépôt argent'), ('Paiement de factures', 'Paiement de factures'), ('Services d’envoi ou de réception de courriers/colis', 'Services d’envoi ou de réception de courriers/colis')], max_length=502)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['nmr'],
            },
        ),
    ]
