# Generated by Django 5.1.2 on 2024-11-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketstrash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='nmr',
            field=models.PositiveIntegerField(),
        ),
    ]
