# Generated by Django 5.1.2 on 2024-11-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_nmr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='nmr',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='ticketstrash',
            name='nmr',
            field=models.PositiveIntegerField(),
        ),
    ]
