# Generated by Django 5.1.2 on 2024-11-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='has_distrubuteur',
            field=models.BooleanField(default=False),
        ),
    ]
